name: client
description: A sign talk app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  record_mp3: ^3.0.0
  font_awesome_flutter: ^10.5.0
  file_picker: ^5.2.5
  youtube_caption_scraper: ^0.1.3
  fluttertoast: ^8.2.1
  youtube_player_flutter: ^8.1.2
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  marquee: ^2.2.3
  connectivity_plus: ^4.0.1
  flutter_gl: ^0.0.21
  three_dart:
    git:
      url: https://github.com/Knightro63/three_dart.git
  three_dart_jsm:
    git:
      url: https://github.com/Knightro63/three_dart_jsm.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/model/
    - assets/images/
    - assets/rive/