name: signtalk
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dependency_validator: ^3.2.2
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  introduction_screen: ^3.1.6
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  record_mp3: ^3.0.0
  rename: ^2.1.1
  rive: ^0.10.3
  video_player: ^2.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/character/
    - assets/rive/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
