synonyms = {
    'joyful': 'happy',
    'pleased': 'happy',
    'content': 'happy',
    'delighted': 'happy',
    'joy': 'happy',
    'elated': 'happy',
    'ecstatic': 'happy',
    'unhappy': 'sad',
    'miserable': 'sad',
    'sorrowful': 'sad',
    'gloomy': 'sad',
    'depressed': 'sad',
    'despondent': 'sad',
    'large': 'big',
    'huge': 'big',
    'enormous': 'big',
    'massive': 'big',
    'gigantic': 'big',
    'colossal': 'big',
    'little': 'small',
    'tiny': 'small',
    'minuscule': 'small',
    'petite': 'small',
    'diminutive': 'small',
    'microscopic': 'small',
    'great': 'good',
    'excellent': 'good',
    'fantastic': 'good',
    'wonderful': 'good',
    'superb': 'good',
    'terrific': 'good',
    'poor': 'bad',
    'terrible': 'bad',
    'awful': 'bad',
    'dreadful': 'bad',
    'unsatisfactory': 'bad',
    'inferior': 'bad',
    'intelligent': 'smart',
    'clever': 'smart',
    'bright': 'smart',
    'wise': 'smart',
    'shrewd': 'smart',
    'astute': 'smart',
    'dull': 'stupid',
    'dense': 'stupid',
    'idiotic': 'stupid',
    'foolish': 'stupid',
    'ignorant': 'stupid',
    'unintelligent': 'stupid',
    'humorous': 'funny',
    'amusing': 'funny',
    'comical': 'funny',
    'entertaining': 'funny',
    'hilarious': 'funny',
    'witty': 'funny',
    'grave': 'serious',
    'solemn': 'serious',
    'earnest': 'serious',
    'thoughtful': 'serious',
    'sincere': 'serious',
    'somber': 'serious',
    'attractive': 'beautiful',
    'lovely': 'beautiful',
    'stunning': 'beautiful',
    'gorgeous': 'beautiful',
    'pretty': 'beautiful',
    'handsome': 'beautiful',
    'unattractive': 'ugly',
    'unsightly': 'ugly',
    'hideous': 'ugly',
    'repulsive': 'ugly',
    'grotesque': 'ugly',
    'deformed': 'ugly',
    'aged': 'old',
    'elderly': 'old',
    'mature': 'old',
    'senior': 'old',
    'veteran': 'old',
    'ancient': 'old',
    'juvenile': 'young',
    'adolescent': 'young',
    'youthful': 'young',
    'teenage': 'young',
    'childish': 'young',
    'naive': 'young',
    'wealthy': 'rich',
    'affluent': 'rich',
    'prosperous': 'rich',
    'opulent': 'rich',
    'loaded': 'rich',
    'well-off': 'rich',
    'impoverished': 'poor',
    'needy': 'poor',
    'destitute': 'poor',
    'broke': 'poor',
    'penniless': 'poor',
    'indigent': 'poor',
    'quick': 'fast',
    'rapid': 'fast',
    'speedy': 'fast',
    'swift': 'fast',
    'hasty': 'fast',
    'expeditious': 'fast',
    'sluggish': 'slow',
    'leisurely': 'slow',
    'gradual': 'slow',
    'unhurried': 'slow',
    'languid': 'slow',
    'plodding': 'slow',
    'furious': 'angry',
    'enraged': 'angry',
    'irritated': 'angry',
    'exasperated': 'angry',
    'indignant': 'angry',
    'infuriated': 'angry',
    'serene': 'calm',
    'peaceful': 'calm',
    'tranquil': 'calm',
    'placid': 'calm',
    'composed': 'calm',
    'relaxed': 'calm',
    'adore': 'love',
    'cherish': 'love',
    'treasure': 'love',
    'worship': 'love',
    'idolize': 'love',
    'romanticize': 'love',
    'abhor': 'hate',
    'detest': 'hate',
    'despise': 'hate',
    'loathe': 'hate',
    'scorn': 'hate',
    'revile': 'hate',
    'achievement': 'success',
    'accomplishment': 'success',
    'victory': 'success',
    'triumph': 'success',
    'conquest': 'success',
    'winning': 'success',
    'defeat': 'failure',
    'loss': 'failure',
    'fiasco': 'failure',
    'disaster': 'failure',
    'collapse': 'failure',
    'ruin': 'failure',
    'fresh': 'new',
    'modern': 'new',
    'contemporary': 'new',
    'innovative': 'new',
    'original': 'new',
    'novel': 'new',
    'costly': 'expensive',
    'pricey': 'expensive',
    'high-priced': 'expensive',
    'lavish': 'expensive',
    'extravagant': 'expensive',
    'luxurious': 'expensive',
    'inexpensive': 'cheap',
    'affordable': 'cheap',
    'budget-friendly': 'cheap',
    'economical': 'cheap',
    'bargain': 'cheap',
    'low-cost': 'cheap',
    'challenging': 'difficult',
    'complicated': 'difficult',
    'arduous': 'difficult',
    'tricky': 'difficult',
    'onerous': 'difficult',
    'formidable': 'difficult',
    'simple': 'easy',
    'effortless': 'easy',
    'undemanding': 'easy',
    'uncomplicated': 'easy',
    'trouble-free': 'easy',
    'facile': 'easy',
    'noisy': 'loud',
    'raucous': 'loud',
    'boisterous': 'loud',
    'clamorous': 'loud',
    'uproarious': 'loud',
    'deafening': 'loud',
    'silent': 'quiet',
    'calm': 'quiet',
    'hushed': 'quiet',
    'peaceful': 'quiet',
    'tranquil': 'quiet',
    'serene': 'quiet',
    'lengthy': 'long',
    'prolonged': 'long',
    'extended': 'long',
    'interminable': 'long',
    'protracted': 'long',
    'endless': 'long',
    'brief': 'short',
    'concise': 'short',
    'small': 'short',
    'little': 'short',
    'compact': 'short',
    'curt': 'short',
    'pithy': 'short',
    'courageous': 'brave',
    'fearless': 'brave',
    'valiant': 'brave',
    'heroic': 'brave',
    'bold': 'brave',
    'gallant': 'brave',
    'timid': 'coward',
    'fainthearted': 'coward',
    'craven': 'coward',
    'spineless': 'coward',
    'pusillanimous': 'coward',
    'timorous': 'coward',
    'compassionate': 'kind',
    'generous': 'kind',
    'benevolent': 'kind',
    'gracious': 'kind',
    'humane': 'kind',
    'charitable': 'kind',
    'ruthless': 'cruel',
    'vicious': 'cruel',
    'sadistic': 'cruel',
    'inhumane': 'cruel',
    'ferocious': 'cruel',
    'merciless': 'cruel',
    'impartial': 'fair',
    'just': 'fair',
    'equitable': 'fair',
    'unbiased': 'fair',
    'evenhanded': 'fair',
    'objective': 'fair',
    'biased': 'unfair',
    'partial': 'unfair',
    'prejudiced': 'unfair',
    'discriminatory': 'unfair',
    'uneven': 'unfair',
    'inequitable': 'unfair',
    'innovative': 'creative',
    'imaginative': 'creative',
    'original': 'creative',
    'artistic': 'creative',
    'inventive': 'creative',
    'resourceful': 'creative',
    'boring': 'dull',
    'tedious': 'dull',
    'uninteresting': 'dull',
    'mundane': 'dull',
    'lackluster': 'dull',
    'drab': 'dull',
    'pure': 'clean',
    'sanitary': 'clean',
    'spotless': 'clean',
    'immaculate': 'clean',
    'tidy': 'clean',
    'hygienic': 'clean',
    'filthy': 'dirty',
    'squalid': 'dirty',
    'grubby': 'dirty',
    'muddy': 'dirty',
    'dingy': 'dirty',
    'foul': 'dirty',
    'fatigued': 'exhausted',
    'weary': 'exhausted',
    'spent': 'exhausted',
    'drained': 'exhausted',
    'exhausted': 'exhausted',
    'worn-out': 'exhausted',
    'vigorous': 'energetic',
    'dynamic': 'energetic',
    'vital': 'energetic',
    'lively': 'energetic',
    'active': 'energetic',
    'robust': 'energetic',
    'bountiful': 'generous',
    'charitable': 'generous',
    'unselfish': 'generous',
    'magnanimous': 'generous',
    'openhanded': 'generous',
    'liberal': 'generous',
    'avaricious': 'greedy',
    'covetous': 'greedy',
    'rapacious': 'greedy',
    'selfish': 'greedy',
    'grasping': 'greedy',
    'acquisitive': 'greedy',
    'wholesome': 'healthy',
    'fit': 'healthy',
    'robust': 'healthy',
    'hearty': 'healthy',
    'vibrant': 'healthy',
    'sound': 'healthy',
    'unwholesome': 'unhealthy',
    'unfit': 'unhealthy',
    'sickly': 'unhealthy',
    'ailing': 'unhealthy',
    'feeble': 'unhealthy',
    'frail': 'unhealthy',
    'significant': 'important',
    'crucial': 'important',
    'vital': 'important',
    'essential': 'important',
    'paramount': 'important',
    'indispensable': 'important',
    'trivial': 'unimportant',
    'insignificant': 'unimportant',
    'negligible': 'unimportant',
    'inconsequential': 'unimportant',
    'minor': 'unimportant',
    'petty': 'unimportant',
    'blameless': 'innocent',
    'pure': 'innocent',
    'virtuous': 'innocent',
    'upright': 'innocent',
    'immaculate': 'innocent',
    'guiltless': 'innocent',
    'culpable': 'guilty',
    'blameworthy': 'guilty',
    'responsible': 'guilty',
    'at fault': 'guilty',
    'remorseful': 'guilty',
    'penitent': 'guilty',
    'transparent': 'open',
    'honest': 'open',
    'forthcoming': 'open',
    'candid': 'open',
    'sincere': 'open',
    'frank': 'open',
    'secretive': 'closed',
    'reserved': 'closed',
    'guarded': 'closed',
    'tight-lipped': 'closed',
    'reticent': 'closed',
    'uncommunicative': 'closed',
    'firm': 'strong',
    'powerful': 'strong',
    'mighty': 'strong',
    'robust': 'strong',
    'vigorous': 'strong'
}



import sys
import nltk
import re
# !{sys.executable} -m pip install contractions
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('omw-1.4')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import contractions

def clean_sentence(sentence):
    # remove contraction
    words = contractions.fix(sentence)

    # Remove punctuation
    words = re.sub(r'[^\w\s]', '', words)

    # Tokenize the sentence into words
    words = word_tokenize(words.lower())

    # Remove stop words
    stop_word = ['an','the','as','were','was','am','to','too','be','is','by','so','of']
    words = [word for word in words if word not in stop_word]

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word,pos="v") for word in words]
    words = [lemmatizer.lemmatize(word,pos="a") for word in words]

    # find synonym of the word
    words = [synonyms[word] if word in synonyms else word for word in words]

    # Join the words back into a sentence
    clean_sentence = ' '.join(words)
    return clean_sentence.upper()

sentence = " i ? den?ied should've didn't ran giving great crucial unhappy brown fine well happiness better good great jumps over of the happiest caught catch thinking dog ."
cleaned_sentence = clean_sentence(sentence)
print(cleaned_sentence)